### PR TITLE
Sorted the list :0

### PR DESCRIPTION
**Pull request by spirillen**
Dared to sort the list....

### CODE REVIEW

**Comment by spirillen** [comment]
@krin

@ryanbr

**Comment by ryanbr** [comment]
Not sure if needing sorting,  FOP.py already sorts @spirillen

**Comment by spirillen** [comment]
yeah it just it seems so messy for the eyes and it does not look transparent whether a record is present or partial present, that's why I'll suggest we sort the source list :smiley: 

What is the sort criteria (order) for FOP?

**Comment by ryanbr** [comment]
Alphabetical, `https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_hide.txt`  See elements rather than domains.  `https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt` filtered alphabetically

**Comment by spirillen** [comment]
ok, but this list does neither... of the above!

but it is your call... close ? merge?

**Comment by ryanbr** [comment]
close, even if we did merge it, the moment we ran FOP.py it would just revert it,.

**Pull request closed without merging**
